language: python

matrix:
  include:
    - name: "sdist and coverage"
      sudo: required
      language: python
      python: 3.6
      services: docker
      env: OMP_NUM_THREADS=4
      script:
        - python -m pip install -U setuptools pytest-cov coveralls coverage~=4.5.4
        - python -m pip install -U numpy==1.17.3 cython==0.29.14
        - python -m pip install -r requirements.txt
        - python setup.py sdist -d dist
        - python setup.py --openmp build_ext --inplace
        - python -m pytest --cov gstools --cov-report term-missing -v tests/
        - python -m coveralls

    - name: "Linux py35"
      sudo: required
      language: python
      python: 3.6
      services: docker
      env: CIBW_BUILD="cp35-*"
    - name: "Linux py36"
      sudo: required
      language: python
      python: 3.6
      services: docker
      env: CIBW_BUILD="cp36-*"
    - name: "Linux py37"
      sudo: required
      language: python
      python: 3.6
      services: docker
      env: CIBW_BUILD="cp37-*"
    - name: "Linux py38"
      sudo: required
      language: python
      python: 3.6
      services: docker
      env: CIBW_BUILD="cp38-*"

    - name: "MacOS py35"
      os: osx
      language: generic
      env: CIBW_BUILD="cp35-*"
    - name: "MacOS py36"
      os: osx
      language: generic
      env: CIBW_BUILD="cp36-*"
    - name: "MacOS py37"
      os: osx
      language: generic
      env: CIBW_BUILD="cp37-*"
    - name: "MacOS py38"
      os: osx
      language: generic
      env: CIBW_BUILD="cp38-*"

    - name: "Win py35"
      os: windows
      language: shell
      before_install: choco install python3 --version 3.6.8 --no-progress -y
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - CIBW_BUILD="cp35-*"
    - name: "Win py36"
      os: windows
      language: shell
      before_install: choco install python3 --version 3.6.8 --no-progress -y
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - CIBW_BUILD="cp36-*"
    - name: "Win py37"
      os: windows
      language: shell
      before_install: choco install python3 --version 3.6.8 --no-progress -y
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - CIBW_BUILD="cp37-*"
    - name: "Win py38"
      os: windows
      language: shell
      before_install: choco install python3 --version 3.6.8 --no-progress -y
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - CIBW_BUILD="cp38-*"

env:
  global:
    - TWINE_USERNAME=geostatframework
    - CIBW_BEFORE_BUILD="pip install numpy==1.17.3 cython==0.29.14 setuptools"
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="python -m pytest -v {project}/tests"

script:
  - python -m pip install cibuildwheel==1.0.0
  - python -m cibuildwheel --output-dir dist

after_success:
  - |
    if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
      python -m pip install twine
      python -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*
      if [[ $TRAVIS_TAG ]]; then python -m twine upload --verbose dist/*; fi
    fi

notifications:
  email:
    recipients:
      - info@geostat-framework.org
