language: python

matrix:
  include:
    - name: "Linux py35"
      sudo: required
      language: python
      python: 3.5
      services: docker
      env:
        - PIP=pip
        - CIBW_BUILD="cp35-*"
        - COVER="off"

    # py36 for coverage and sdist
    - name: "Linux py36"
      sudo: required
      language: python
      python: 3.6
      services: docker
      env:
        - PIP=pip
        - CIBW_BUILD="cp36-*"
        - COVER="on"

    # https://github.com/travis-ci/travis-ci/issues/9815
    - name: "Linux py37"
      sudo: required
      language: python
      python: 3.7
      dist: xenial
      services: docker
      env:
        - PIP=pip
        - CIBW_BUILD="cp37-*"
        - COVER="off"

    - name: "MacOS py35"
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD="cp35-*"
        - COVER="off"

    - name: "MacOS py36"
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD="cp36-*"
        - COVER="off"

    - name: "MacOS py37"
      os: osx
      language: generic
      env:
        - PIP=pip2
        - CIBW_BUILD="cp37-*"
        - COVER="off"

env:
  global:
    - TWINE_USERNAME=geostatframework
    - CIBW_BEFORE_BUILD="pip install numpy==1.14.5 cython==0.28.3"
    - CIBW_TEST_REQUIRES=pytest-cov
    # inplace cython build and test run
    - CIBW_TEST_COMMAND="cd {project} && python setup.py build_ext --inplace && py.test --cov gstools --cov-report term-missing -v {project}/tests"

script:
  # create wheels
  - $PIP install cibuildwheel==0.11.1
  - cibuildwheel --output-dir wheelhouse
  # create source dist for pypi and create coverage (only once for linux py3.6)
  - |
    if [[ $COVER == "on" ]]; then
      rm -rf dist
      python -m pip install -U numpy==1.14.5 cython==0.28.3 setuptools
      python -m pip install pytest-cov coveralls
      python -m pip install -r docs/requirements.txt
      python setup.py sdist
      python setup.py build_ext --inplace
      python -m pytest --cov gstools --cov-report term-missing -v tests/
      python -m coveralls
    fi

after_success:
  # pypi upload ("test" allways and "official" on TAG)
  - python -m pip install twine
  - python -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  - python -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*.tar.gz
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m twine upload --verbose --skip-existing wheelhouse/*.whl
      python -m twine upload --verbose --skip-existing dist/*.tar.gz
    fi

notifications:
  email:
    recipients:
    - info@geostat-framework.org
